# Generated by Django 2.2.5 on 2019-09-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('date_of_birth', models.DateTimeField(auto_now=True, verbose_name='Data de Nascimento')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('genre', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Solicitação',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('date', models.DateField(auto_now=True, max_length=100, null=True, verbose_name='Data')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Setor')),
            ],
        ),
    ]
