# Generated by Django 2.2.5 on 2019-09-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190919_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='solicitação',
            old_name='date',
            new_name='data',
        ),
    ]
